# ==== The code below creates the deal data structures for BondLabSMBS ==


MakeSchedule(bond.id = "BondLabMBS4",
                DealName = "BondLabPACInverse",
                Group = 1,
                original.bal = 200000000,
                first.pmtdate = "01-25-2013",
                trade.date = "01-10-2013",
                settlement.date = "01-13-2013",
                price = 105.75,
                begin.cpr = .2,
                end.cpr = 6,
                seasoning.period = 30,
                lower.PSA = 75, 
                upper.PSA = 250)

MakeRAID(DealName = "BondLabPACInverse", 
             Issuer = "Bondlab", 
             DealPriceDate = "12-01-2012", 
             DealSettlementDate = "01-01-2013",
             Underwriter = "Bondlab",
             NumberofTranches = 4,
             NumberPacSchedules = 1,
             NumberofGroups = 1,
             DealSize = 200000000,
             CollateralAmount = 200000000)
      
    MakeCollateral(DealName = "BondLabPACInverse",
                   Group = 1,
                   Cusip = list("bondlabMBS4"),
                   OrigBal = list("200000000"))
     
    MakeTranche(DealName = "BondLabPACInverse",
                TrancheNumber = "1",
                TrancheName = "A",
                TranchePrincipal = "Pass_Through",
                TrancheInterest = "Fix",
                TranchePrincipalDesc = "PAC",
                TrancheInterestDesc = "Fix",
                Cusip = "BondLabPAC2",
                TrancheOrigBal = 148769215,
                TrancheDatedDate  = "01-01-2013",
                TrancheFirstPmtDate = "01-15-2013",
                TrancheLastPmtDate = "12-15-2042",
                TrancheNextPmtDate = "01-15-2013",
                TrancheCoupon = 2.25,
                Delay = 15,
                PrinPmtFrequency = 12,
                InterestPmtFrequency = 12,
                FloaterIndex = "999",
                FloaterMargin = 0,
                FloaterCap = 1.41,
                FloaterFloor = 1.41,
                FloaterFormula = 0,
                PacLowBand = 75,
                PacHighBand = 250,
                Group = 1,
                Schedule = TRUE,
                Fixed = TRUE)
      
      MakeTranche(DealName = "BondLabPACInverse",
                  TrancheNumber = "2",
                  TrancheName = "B",
                  TranchePrincipal = "Pass_Through",
                  TrancheInterest = "Float",
                  TranchePrincipalDesc = "CMP",
                  TrancheInterestDesc = "Floater",
                  Cusip = "BondLabFloater",
                  TrancheOrigBal = 30738471,
                  TrancheDatedDate  = "01-01-2013",
                  TrancheFirstPmtDate = "01-15-2013",
                  TrancheLastPmtDate = "12-15-2042",
                  TrancheNextPmtDate = "01-15-2013",
                  TrancheCoupon = 0.55,
                  Delay = 15,
                  PrinPmtFrequency = 12,
                  InterestPmtFrequency = 12,
                  FloaterIndex = "1Mo. LIBOR",
                  FloaterMargin = .30,
                  FloaterCap = 6.66,
                  FloaterFloor = 0.33,
                  FloaterFormula = function(Index = "vector", FloaterCap = "numeric", FloaterMargin = "numeric", FloaterFloor = "numeric")
                                    {min(FloaterCap, max((Index + FloaterMargin), FloaterFloor))},
                  PacLowBand = 000,
                  PacHighBand = 000,
                  Group = 1,
                  Schedule = TRUE,
                  Fixed = FALSE)

    MakeTranche(DealName = "BondLabPACInverse",
                  TrancheNumber = "3",
                  TrancheName = "C",
                  TranchePrincipal = "Pass_Through",
                  TrancheInterest = "Float",
                  TranchePrincipalDesc = "CMP",
                  TrancheInterestDesc = "Inverse Floater",
                  Cusip = "BondLabInverse",
                  TrancheOrigBal = 20492314,
                  TrancheDatedDate  = "01-01-2013",
                  TrancheFirstPmtDate = "01-15-2013",
                  TrancheLastPmtDate = "12-15-2042",
                  TrancheNextPmtDate = "01-15-2013",
                  TrancheCoupon = 8.91,
                  Delay = 15,
                  PrinPmtFrequency = 12,
                  InterestPmtFrequency = 12,
                  FloaterIndex = "1Mo. LIBOR",
                  FloaterMargin = 9.21,
                  FloaterCap = 9.21,
                  FloaterFloor = 0.00,
                  FloaterFormula = function(Index = "vector", FloaterCap = "numeric", FloaterMargin = "numeric", FloaterFloor = "numeric")
                                   {min(FloaterCap, max((-1.5 * Index + FloaterMargin), FloaterFloor)},
                  PacLowBand = 000,
                  PacHighBand = 000,
                  Group = 1,
                  Schedule = TRUE,
                  Fixed = FALSE)

    MakeTranche(DealName = "BondLabPACInverse",
                TrancheNumber = "4",
                TrancheName = "D",
                TranchePrincipal = "Pass_Through",
                TrancheInterest = "Float",
                TranchePrincipalDesc = "NTL",
                TrancheInterestDesc = "Floater",
                Cusip = "BondLabPACIO",
                TrancheOrigBal = 148769215,
                TrancheDatedDate  = "01-01-2013",
                TrancheFirstPmtDate = "01-15-2013",
                TrancheLastPmtDate = "12-15-2042",
                TrancheNextPmtDate = "01-15-2013",
                TrancheCoupon = 1.75,
                Delay = 15,
                PrinPmtFrequency = 12,
                InterestPmtFrequency = 12,
                FloaterIndex = "999",
                FloaterMargin = 0,
                FloaterCap = 1.75,
                FloaterFloor = 1.75,
                FloaterFormula = function(Index = "vector", FloaterCap = "numeric", FloaterMargin = "numeric", FloaterFloor = "numeric")
                                 {min(FloaterCap, (max(Index + FloaterMargin, FloaterFloor)))},
                PacLowBand = 75,
                PacHighBand = 250,
                Group = 1,
                Schedule = TRUE,
                Fixed = TRUE)

  
      MakeRDME(DealName = "BondLabPACInverse",
               TrancheNumber = 1,
               Cusip = "BondLabPAC2",
               PaymentDate = "01-01-2013",
               Coupon = 2.25,
               Factor = 1)
      
      MakeRDME(DealName = "BondLabPACInverse",
               TrancheNumber = 2,
               Cusip = "BondLabFltr",
               PaymentDate = "1-01-2013",
               Coupon = 0.55,
               Factor = 1)

      MakeRDME(DealName = "BondLabPACInverse",
              TrancheNumber = 3,
              Cusip = "BondLabCMP1",
              PaymentDate = "1-01-2013",
              Coupon = 9.21,
              Factor = 1)

      MakeRDME(DealName = "BondLabPACInverse",
            TrancheNumber = 4,
            Cusip = "BondLabPACIO",
            PaymentDate = "1-01-2013",
            Coupon = 1.75,
            Factor = 1)

  
    RemicStructure("BondLabPACInverse")   
    
    REMIC <- readRDS("~/BondLab/REMICData/BondLabPACInverse.rds")

   
