---
title: "Bond Lab Structuring"
author: "Glenn M. Schultz"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{REMIC structuring with Bond Lab}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```{r, echo = FALSE, results = 'hide', warning=FALSE, message=FALSE}
require(BondLab)
```


# Introduction
The Bond Lab structuring tool is based on the followng objects:

* REMIC At Issuance Disclosure Data (RAID)
* REMIC Disclosure Month End (RDME)
* Tranches
* Collateral Group
* Schedules
* Waterfall

The following example illustrates structuring a simple IO/PO transaction.  The following illustrates the structuring steps for FNMA Strip Trust 416.

First, structure the collateral information as given by the relay file at issuance.  Structure the collateral group using the MakeMBSDetails function.  This saves the collateral group information in the BondData folder. Future versions BondLab will include a make CollateralDetail and data folder structure. 
``` r
  MakeMBSDetails(
    Cusip = "FNM1900416",
    ID = "FNM1900416",
    BondType = "MBS",
    Sector = "PassThrough",
    Coupon = 4.000,
    IssueDate = "10-01-2012",
    DatedDate = "10-01-2012",
    Maturity = "03-01-2042",
    LastPmtDate ="10-01-2012",
    NextPmtDate = "11-01-2012",
    PaymentDelay = 24,
    Moody = "Aaa",
    SP = "AAA",
    BondLab = "AAA",
    Frequency = 12,
    BondBasis = "30360",
    GWac = 4.53,
    OrigLoanBal = 230000,
    OrigLTV = 150,
    AmortizationType = "fixed",
    AmortizationTerm = 360,
    Index = "none",
    Margin = 0,
    FirstPmtDate = "03-01-2012",
    FinalPmtDate = "03-01-2041",
    Servicing = 0.25,
    Gfee = 0.25,
    InitialInterest = FALSE,
    InterestOnlyPeriod = 0,
    FirstPrinPaymentDate = "00-00-0000",
    BalloonPmt = FALSE,
    BalloonDate = "00-00-0000",
    MBSFactor = 1,
    Model = "FH30.Generic",
    Burnout = 25,
    SATO = 0.50
  )
```
## The RAID file - REMIC At Issuance Disclosure file.  
Second, create The RAID file.  This file is the indicative data for the REMIC at issuance.  The RAID object is save in the RAID folder.  The slots for this class are 100% compliant to the FNMA relay files.
``` r
  MakeMBSDetails(
    Cusip = "FNM1900416",
    ID = "FNM1900416",
    BondType = "MBS",
    Sector = "PassThrough",
    Coupon = 4.000,
    IssueDate = "10-01-2012",
    DatedDate = "10-01-2012",
    Maturity = "03-01-2042",
    LastPmtDate ="10-01-2012",
    NextPmtDate = "11-01-2012",
    PaymentDelay = 24,
    Moody = "Aaa",
    SP = "AAA",
    BondLab = "AAA",
    Frequency = 12,
    BondBasis = "30360",
    GWac = 4.53,
    OrigLoanBal = 230000,
    OrigLTV = 150,
    AmortizationType = "fixed",
    AmortizationTerm = 360,
    Index = "none",
    Margin = 0,
    FirstPmtDate = "03-01-2012",
    FinalPmtDate = "03-01-2041",
    Servicing = 0.25,
    Gfee = 0.25,
    InitialInterest = FALSE,
    InterestOnlyPeriod = 0,
    FirstPrinPaymentDate = "00-00-0000",
    BalloonPmt = FALSE,
    BalloonDate = "00-00-0000",
    MBSFactor = 1,
    Model = "FH30.Generic",
    Burnout = 25,
    SATO = 0.50
  )
```


## Create the collateral group underlying the REMIC transaction

Third, create the collateral group object.  For the first structuring pass use the collateral information created above.  The collateral group object is designed to hold multiple groups or pools.  The REMIC cashflow engine logic needs to be completed.  Future versions of BondLab will allow for collateral information or expand to pools.

``` r
    MakeCollateral(
      DealName = "FNS416",
      Group = 1,
      Cusip = list("FNM1900416"),
      OrigBal = list(275000000)
    )
```    

## Create the Tranche data for REMIC

Fourth, create the tranche data for the REMIC using the MakeTranche function.  Rinse and repeat for as many times needed.
``` r
  MakeTranche(
      DealName = "FNS416",
      TrancheNumber = "1",
      NumberofComponents = 0,
      ComponentofTranches = "",
      TrancheName = "416-A150",
      TranchePrincipalDesc = "PassThrough",
      TrancheInterestDesc = "Fix",
      TrancheOtherDescription = "None",
      Cusip = "31395QTK6",
      TrancheOrigBal = 137500000,
      TrancheInterest = "Fix",
      TrancheCoupon = 1.50,
      AccrualRate = 0.00,
      TreasuryMaturity = 0,
      TreasuryYield = 0.000,
      TreasurySpread = 0.000,
      TrancheYield = 0.000,
      TranchePrice = 0.000,
      TrancheProceedsWithInterest = 0.000,
      TrancheAvgLife = 7.285,
      TrancheDuration = 0.000,
      TrancheDatedDate = "10-01-2012",
      TrancheFirstPmtDate = "11-25-2012",
      TrancheLastPmtDate = "03-25-2042",
      TrancheFinalPmtDate = "11-25-2042",
      Delay = 24,
      InterestPmtFrequency = 12,
      PrinPmtFrequency = 12,
      PacLowBand = 0,
      PacHighBand = 0,
      FloaterIndex = "NA",
      InitialIndexValue = 0,
      FloaterMargin = 0,
      FloaterMultiplier = 1,
      FloaterCap = 0,
      FloaterFloor = 0,
      FloaterInitialCoupon = 0,
      FloaterResetFrequency = 0,
      FloaterFirstResetDate = "00-00-0000",
      FloaterFormula = function(){},
      Group = 1,
      TrancheType = "Exchangable",
      Schedule = FALSE,
      Fixed = FALSE)
  )
```
Floating rate tranches represent a case where one needs to include a function as shown below. The floater formula is added to the slot.  Future versions of BondLab including prototyping of classes may default to the floater formula 
``` r
 MakeTranche(
      DealName = "FNS416",
      TrancheNumber = "2",
      NumberofComponents = 0,
      ComponentofTranches = "",
      TrancheName = "416-F4",
      TranchePrincipalDesc = "PassThrough",
      TrancheInterestDesc = "Float",
      TrancheOtherDescription = "None",
      Cusip = "31395QTL4",
      TrancheOrigBal = 137500000,
      TrancheInterest = "Float",
      TrancheCoupon = 0.80,
      AccrualRate = 0.00,
      TreasuryMaturity = 0,
      TreasuryYield = 0.000,
      TreasurySpread = 0.000,
      TrancheYield = 0.000,
      TranchePrice = 0.000,
      TrancheProceedsWithInterest = 0.000,
      TrancheAvgLife = 7.285,
      TrancheDuration = 5.07,
      TrancheDatedDate = "10-25-2012",
      TrancheFirstPmtDate = "11-25-2012",
      TrancheLastPmtDate = "03-25-2042",
      TrancheFinalPmtDate = "11-25-2042",
      Delay = 0,
      InterestPmtFrequency = 12,
      PrinPmtFrequency = 12,
      PacLowBand = 0,
      PacHighBand = 0,
      FloaterIndex = "LIBOR1BBA",
      InitialIndexValue = .25,
      FloaterMargin = .55,
      FloaterMultiplier = 1,
      FloaterCap = 6.50,
      FloaterFloor = 0.55,
      FloaterInitialCoupon = 0.80,
      FloaterResetFrequency = 12,
      FloaterFirstResetDate = "11-25-2012",
      FloaterFormula = function(Index = "numeric", 
      FloaterCap = "numeric",FloaterMargin = "numeric", FloaterFloor = "numeric")
      {min(FloaterCap, max((Index + FloaterMargin), FloaterFloor))},
      Group = 1,
      TrancheType = "Exchangable",
      Schedule = FALSE,
      Fixed = FALSE)
```



## Create the REMIC Month End Disclosure file (RDME)

   + **DealName** The deal name
   + **TrancheNumber** The tranche number
   + **Cusip** The tranche cusip number
   + **PaymentDate** The tranche payment date
   + **Coupon** The bond coupon rate struck for each month
   + **Factor** The tranche factor

A RDME file must be created for each tranche.  The RDME file stores the history of the payment date,
tranche coupon, and tranche factor.  The Bond Lab MakeRDME function help file provides additional detail to create
the RDME file

  
## Call the REMIC constructor function

Once the objects are created and saved call the REMICStructure function.  This function creates the REMIC umbrella and saves tranche to the BondData folder



## The last step is to write the waterfall and save in the Waterfall folder