


MBSDetails <- function(
  Cusip = "character",
  ID = "character",
  BondType = "character",
  Sector ="character",
  Coupon = numeric(),
  IssueDate = "character",
  DatedDate = "character",
  Maturity = "character",
  LastPmtDate = "character",
  NextPmtDate = "character",
  PaymentDelay = numeric(),
  Moody = "character",
  SP = "character",
  BondLab  = "character",
  Frequency = numeric(),
  BondBasis = "character",
  GWac = numeric(),
  AmortizationType = "character",
  AmortizationTerm = numeric(),
  Index = "character",
  Margin = numeric(),
  FirstPmtDate = "character",
  FinalPmtDate = "character",
  Servicing = numeric(),
  PMI = numeric(),
  Gfee = numeric(),
  InitialInterest = "character",
  InterestOnlyPeriod = numeric(),
  FirstPrinPaymentDate = "character",
  BalloonPmt = "character",
  BalloonDate = "character",
  MBSFactor = numeric(),
  Model = "character",
  Burnout = numeric(),
  SATO = numeric()
) {
  
  new("MBSDetails",
      Cusip = Cusip,
      ID = ID,
      BondType = BondType,
      Sector = Sector,
      Coupon = Coupon,
      IssueDate = IssueDate,
      DatedDate = DatedDate,
      Maturity = Maturity,
      LastPmtDate = LastPmtDate,
      NextPmtDate = NextPmtDate,
      PaymentDelay = PaymentDelay,
      Moody = Moody,
      SP = SP,
      BondLab  = BondLab,
      Frequency = Frequency,
      BondBasis = BondBasis,
      GWac = GWac,
      AmortizationType = AmortizationType,
      AmortizationTerm = AmortizationTerm,
      Index = Index,
      Margin = Margin,
      FirstPmtDate = FirstPmtDate,
      FinalPmtDate = FinalPmtDate,
      Servicing = Servicing,
      PMI = PMI,
      Gfee = Gfee,
      InitialInterest = InitialInterest,
      InterestOnlyPeriod = InterestOnlyPeriod,
      FirstPrinPaymentDate = FirstPrinPaymentDate,
      BalloonPmt = BalloonPmt,
      BalloonDate = BalloonDate,
      MBSFactor = MBSFactor,
      Model = Model,
      Burnout = Burnout,
      SATO = SATO)
}

MakeMBSDetails <- function(
  Cusip = "character",
  ID = "character",
  BondType = "character",
  Sector ="character",
  Coupon = numeric(),
  IssueDate = "character",
  DatedDate = "character",
  Maturity = "character",
  LastPmtDate = "character",
  NextPmtDate = "character",
  PaymentDelay = numeric(),
  Moody = "character",
  SP = "character",
  BondLab  = "character",
  Frequency = numeric(),
  BondBasis = "character",
  GWac = numeric(),
  AmortizationType = "character",
  AmortizationTerm = numeric(),
  Index = "character",
  Margin = numeric(),
  FirstPmtDate = "character",
  FinalPmtDate = "character",
  Servicing = numeric(),
  PMI = numeric(),
  Gfee = numeric(),
  InitialInterest = "character",
  InterestOnlyPeriod = numeric(),
  FirstPrinPaymentDate = "character",
  BalloonPmt = "character",
  BalloonDate = "character",
  MBSFactor = numeric(),
  Model = "character",
  Burnout = numeric(),
  SATO = numeric())
{
  
  temp <- MBSDetails(
    Cusip = Cusip,
    ID = ID,
    BondType = BondType,
    Sector = Sector,
    Coupon = Coupon,
    IssueDate = IssueDate,
    DatedDate = DatedDate,
    Maturity = Maturity,
    LastPmtDate = LastPmtDate,
    NextPmtDate = NextPmtDate,
    PaymentDelay = PaymentDelay,
    Moody = Moody,
    SP = SP,
    BondLab  = BondLab,
    Frequency = Frequency,
    BondBasis = BondBasis,
    GWac = GWac,
    AmortizationType = AmortizationType,
    AmortizationTerm = AmortizationTerm,
    Index = Index,
    Margin = Margin,
    FirstPmtDate = FirstPmtDate,
    FinalPmtDate = FinalPmtDate,
    Servicing = Servicing,
    PMI = PMI,
    Gfee = Gfee,
    InitialInterest = InitialInterest,
    InterestOnlyPeriod = InterestOnlyPeriod,
    FirstPrinPaymentDate = FirstPrinPaymentDate,
    BalloonPmt = BalloonPmt,
    BalloonDate = BalloonDate,
    MBSFactor = MBSFactor,
    Model = Model,
    Burnout = Burnout,
    SATO = SATO)
  
  connMBSDeails <- gzfile(description = paste("~/BondLab/BondData/",temp@ID,".rds", sep = ""))
  saveRDS(temp, connMBSDeails)
  
  
}

MakeMBSDetails( Cusip = "23456789",
                ID = "bondlabMBS4",
                BondType = "MBS",
                Sector = "MBS",
                Coupon = 4.0,
                IssueDate = "01-01-2013",
                DatedDate = "01-01-2013",
                Maturity = "01-01-2043",
                LastPmtDate = "01-01-2013",
                NextPmtDate = "02-01-2013",
                PaymentDelay = 24,     
                Moody = "Aaa",
                SP = "AAA",
                BondLab = "Aaa",
                Frequency = 12,
                BondBasis = "30360",
                GWac = 4.75,
                AmortizationType = "fixed",
                AmortizationTerm = 30,     
                Index = "None",
                Margin = 0,
                FirstPmtDate = "01-01-2013",
                FinalPmtDate = "01-01-2043",
                Servicing = 0.25,
                PMI = 0.25,
                Gfee = 0.25,
                InitialInterest = "no",
                InterestOnlyPeriod = 0,
                FirstPrinPaymentDate = "1-01-2013",
                BalloonPmt = "no",
                BalloonDate = "00-00-0000",
                MBSFactor = 1,
                Model = "FH30.Generic",
                Burnout = 25,
                SATO = 0.75
)
